model:
  name: "resnet50"
  num_classes: 1000
  pretrained: false

data:
  root: "/path/to/imagenet"
  batch_size: 256
  num_workers: 4
  image_size: 224

training:
  epochs: 90
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  lr_schedule:
    milestones: [30, 60, 80]
    gamma: 0.1

transforms:
  train:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225] 